INSERT INTO `_string` (`stringid`, `stringpg`, `stringlang`, `stringtype`, `stringtitle`, `stringentry`) VALUES
(NULL, '', 'zh', 'help', 'admin', 'Administrative staff accounts can be created edited and deleted under this section. You can also assign privileges.'),
(NULL, '', 'zh', 'help', 'user', 'Create new users or modify and delete existing ones through this panel. Members have access to similar forms through their own account. You can also connect them with other modules as well as insert pictures and documents.'),
(NULL, '', 'zh', 'help', 'newsletter', 'Send a newsletter to the members and manage sent ones. You may also forward it to additional emails.'),
(NULL, '', 'zh', 'help', 'string', 'Edit all the strings that appear on the site either in admin or not. Caution, some changes might produce undesirable results especially submit buttons.'),
(NULL, '', 'zh', 'help', 'bannedip', 'Listing of all the IP that have been blocked by the blog system, you may also insert new ones and delete some.'),
(NULL, '', 'zh', 'help', 'communications', 'This section offers a form similar to a contact page except the fact that you can choose groups to send it to. Members also have access to this form.'),
(NULL, '', 'zh', 'help', 'media', 'This is where all the media files like images documents and videos or others can be managed as well as through each modules and pages forms.'),
(NULL, '', 'zh', 'help', 'event', 'Create events or modify and delete existing ones.'),
(NULL, '', 'zh', 'help', 'gallery', 'Create galleries or modify and delete existing ones. To upload you may also use the zip functionality for full gallery or one by one.'),
(NULL, '', 'zh', 'help', 'forum', 'Manage the posts left by the members. This is also where you may select IPs to be denied.'),
(NULL, '', 'zh', 'general', 'achoisir', 'to Choose'),
(NULL, '', 'zh', 'general', 'acceder', 'Accessing'),
(NULL, '', 'zh', 'general', 'acces', 'Access'),
(NULL, '', 'zh', 'general', 'accordusage', 'By clicking you accept to receive the newsletter (Email addresses submitted will neither be published nor sold !)'),
(NULL, '', 'zh', 'general', 'accueil', 'Homepage'),
(NULL, '', 'zh', 'general', 'admin', 'Admin'),
(NULL, '', 'zh', 'general', 'admincheckconf', 'The Administration has received your registration request and will confirm it via email within 24 hours. Thank you!'),
(NULL, '', 'zh', 'general', 'adresse', 'Address'),
(NULL, '', 'zh', 'general', 'adressecomp', 'Complete Address'),
(NULL, '', 'zh', 'general', 'aenvoyer', 'to send'),
(NULL, '', 'zh', 'general', 'aide', 'Help'),
(NULL, '', 'zh', 'general', 'ajout', 'New'),
(NULL, '', 'zh', 'general', 'ajouter', 'Add'),
(NULL, '', 'zh', 'general', 'analytics', 'Analytics'),
(NULL, '', 'zh', 'general', 'anonyme', 'Anonymous'),
(NULL, '', 'zh', 'general', 'archive', 'Archive'),
(NULL, '', 'zh', 'general', 'archived', 'Archived'),
(NULL, '', 'zh', 'general', 'ASC', 'Ascending'),
(NULL, '', 'zh', 'general', 'aujourdhui', 'today'),
(NULL, '', 'zh', 'general', 'batch', 'Batch'),
(NULL, '', 'zh', 'general', 'bakdb', 'Do a backup of the database'),
(NULL, '', 'zh', 'general', 'bannedip', 'Banned IPs'),
(NULL, '', 'zh', 'general', 'bientot', 'soon'),
(NULL, '', 'zh', 'general', 'bienvenue', 'Welcome'),
(NULL, '', 'zh', 'general', 'bloginfo', 'blog info'),
(NULL, '', 'zh', 'general', 'calendrier', 'calendar'),
(NULL, '', 'zh', 'general', 'cettepage', 'this page'),
(NULL, '', 'zh', 'general', 'changer', 'Change'),
(NULL, '', 'zh', 'general', 'cher', 'Dear'),
(NULL, '', 'zh', 'general', 'choisir', 'Choose'),
(NULL, '', 'zh', 'general', 'cliquerici', 'Click here'),
(NULL, '', 'zh', 'general', 'code', 'code'),
(NULL, '', 'zh', 'general', 'codpost', 'ZIP Code'),
(NULL, '', 'zh', 'general', 'compagnie', 'Company'),
(NULL, '', 'zh', 'general', 'comment', 'Comment'),
(NULL, '', 'zh', 'general', 'comments', 'Comment'),
(NULL, '', 'zh', 'general', 'communications', 'communications'),
(NULL, '', 'zh', 'general', 'config', 'Config'),
(NULL, '', 'zh', 'general', 'confinfo', 'conf info'),
(NULL, '', 'zh', 'general', 'confirmation', 'Confirmation'),
(NULL, '', 'zh', 'general', 'confirmationeffacement', 'Are you sure you want to delete ?'),
(NULL, '', 'zh', 'general', 'confirme', 'confirmed'),
(NULL, '', 'zh', 'general', 'confirmer', 'Confirm'),
(NULL, '', 'zh', 'general', 'coords', 'Coordinates'),
(NULL, '', 'zh', 'general', 'copyrightnotice', 'Webdevelopment by <a href=http://www.mediavince.com target=_blank>Media Vince</a> &copy; '),
(NULL, '', 'zh', 'general', 'credentials', 'Credentials'),
(NULL, '', 'zh', 'general', 'date', 'Date posted'),
(NULL, '', 'zh', 'general', 'datecree', 'Date Created'),
(NULL, '', 'zh', 'general', 'datenaissance', 'Date of birth'),
(NULL, '', 'zh', 'general', 'de', 'of'),
(NULL, '', 'zh', 'general', 'deja', 'already'),
(NULL, '', 'zh', 'general', 'dejaexistant', 'already existing'),
(NULL, '', 'zh', 'general', 'derequete', 'of request'),
(NULL, '', 'zh', 'general', 'dernier', 'Last'),
(NULL, '', 'zh', 'general', 'derniere', 'Last'),
(NULL, '', 'zh', 'general', 'DESC', 'Descending'),
(NULL, '', 'zh', 'general', 'description', 'Description'),
(NULL, '', 'zh', 'general', 'destinataire', 'send to'),
(NULL, '', 'zh', 'general', 'detexte', 'of text'),
(NULL, '', 'zh', 'general', 'dispo', 'available'),
(NULL, '', 'zh', 'general', 'doc', 'document'),
(NULL, '', 'zh', 'general', 'docdispo', 'available document'),
(NULL, '', 'zh', 'general', 'efface', 'erased'),
(NULL, '', 'zh', 'general', 'effacer', 'Erase'),
(NULL, '', 'zh', 'general', 'effectue', 'done'),
(NULL, '', 'zh', 'general', 'email', 'Email'),
(NULL, '', 'zh', 'general', 'enattente', 'on hold'),
(NULL, '', 'zh', 'general', 'enregistre', 'recorded'),
(NULL, '', 'zh', 'general', 'enregistrement', 'Record'),
(NULL, '', 'zh', 'general', 'erreur', 'Error'),
(NULL, '', 'zh', 'general', 'entrer', 'Login'),
(NULL, '', 'zh', 'general', 'envoidoc', 'Upload the Document'),
(NULL, '', 'zh', 'general', 'envoiphoto', 'Upload the Picture'),
(NULL, '', 'zh', 'general', 'envoye', 'sent'),
(NULL, '', 'zh', 'general', 'envoyer', 'Send'),
(NULL, '', 'zh', 'general', 'event', 'event'),
(NULL, '', 'zh', 'general', 'existant', 'found'),
(NULL, '', 'zh', 'general', 'fichier', 'File'),
(NULL, '', 'zh', 'general', 'forgotpass', 'I forgot my password'),
(NULL, '', 'zh', 'general', 'forgotpasshelp', '<b>Follow these instructions:</b><br />> Input your username<br />> Check that box<br />> Click login<br />A new password will be sent to the email address on file!'),
(NULL, '', 'zh', 'general', 'forum', 'Forum'),
(NULL, '', 'zh', 'general', 'from', 'From'),
(NULL, '', 'zh', 'general', 'gallery', 'Gallery'),
(NULL, '', 'zh', 'general', 'gendre', 'Civil Status'),
(NULL, '', 'zh', 'general', 'gestion', 'Manage'),
(NULL, '', 'zh', 'general', 'heure', 'hour'),
(NULL, '', 'zh', 'general', 'identifierencore', 'Please login again.'),
(NULL, '', 'zh', 'general', 'img', 'Image'),
(NULL, '', 'zh', 'general', 'infodb', 'DB Infos'),
(NULL, '', 'zh', 'general', 'invalide', 'invalid'),
(NULL, '', 'zh', 'general', 'jour', 'Day'),
(NULL, '', 'zh', 'general', 'laisservidepourgarder', 'Leave blank to keep actual one'),
(NULL, '', 'zh', 'general', 'langue', 'Language'),
(NULL, '', 'zh', 'general', 'lesautrespages', 'the other pages'),
(NULL, '', 'zh', 'general', 'listecorrection', 'Please correct what is listed in red!'),
(NULL, '', 'zh', 'general', 'logo', 'Logo'),
(NULL, '', 'zh', 'general', 'manquant', 'missing'),
(NULL, '', 'zh', 'general', 'map', 'map'),
(NULL, '', 'zh', 'general', 'marketing1', 'More info about me'),
(NULL, '', 'zh', 'general', 'max', 'Maximum'),
(NULL, '', 'zh', 'general', 'media', 'Media'),
(NULL, '', 'zh', 'general', 'membre', 'Member'),
(NULL, '', 'zh', 'general', 'menu', 'menu'),
(NULL, '', 'zh', 'general', 'metadesc', 'Meta description'),
(NULL, '', 'zh', 'general', 'metakeyw', 'Key words'),
(NULL, '', 'zh', 'general', 'mettreenattente', 'Place on hold'),
(NULL, '', 'zh', 'general', 'message', 'Message'),
(NULL, '', 'zh', 'general', 'min', 'Minimum'),
(NULL, '', 'zh', 'general', 'moderateurverif', '(The Forum and the comments are moderated, and will not appear on this site until the editor has approved them)'),
(NULL, '', 'zh', 'general', 'modification', 'Modification'),
(NULL, '', 'zh', 'general', 'modifie', 'modified'),
(NULL, '', 'zh', 'general', 'modifier', 'Modify'),
(NULL, '', 'zh', 'general', 'module', 'Module'),
(NULL, '', 'zh', 'general', 'mois', 'month'),
(NULL, '', 'zh', 'general', 'motdepasse', 'Password'),
(NULL, '', 'zh', 'general', 'multimedia', 'Multimedia'),
(NULL, '', 'zh', 'general', 'N', 'No'),
(NULL, '', 'zh', 'general', 'name', 'Name'),
(NULL, '', 'zh', 'general', 'newsletter', 'Newsletter'),
(NULL, '', 'zh', 'general', 'nl_adhesionprete', 'We are pleased to announce that your registration is ready.<br /> <br />You will find your personal details to enter the login section below.'),
(NULL, '', 'zh', 'general', 'nl_copiercoller', 'Please click or copy and paste this link in a new window'),
(NULL, '', 'zh', 'general', 'nl_liresursite', 'For you to read this page on'),
(NULL, '', 'zh', 'general', 'nl_messagepreview', 'Here is a preview of what each registered members will receive'),
(NULL, '', 'zh', 'general', 'nl_sepadressesemail', '(seperate each email addresses by a coma and one space : &acute;, &acute;)'),
(NULL, '', 'zh', 'general', 'nom', 'Name'),
(NULL, '', 'zh', 'general', 'nomutil', 'Username'),
(NULL, '', 'zh', 'general', 'non', 'NOT'),
(NULL, '', 'zh', 'general', 'nouveau', 'new'),
(NULL, '', 'zh', 'general', 'nouveaumdpachanger', 'Your new password has been sent to your email address, please update it upon your next login!'),
(NULL, '', 'zh', 'general', 'nphoto', 'Number of Photos'),
(NULL, '', 'zh', 'general', 'num', 'Number'),
(NULL, '', 'zh', 'general', 'numfax', 'FAX Number'),
(NULL, '', 'zh', 'general', 'numid', 'ID Number'),
(NULL, '', 'zh', 'general', 'numtel', 'Phone Number'),
(NULL, '', 'zh', 'general', 'obligatoire', 'mandatory'),
(NULL, '', 'zh', 'general', 'optdb', 'Optimize the database'),
(NULL, '', 'zh', 'general', 'options', 'Options'),
(NULL, '', 'zh', 'general', 'ordre', 'Order'),
(NULL, '', 'zh', 'general', 'organisation', 'Organization'),
(NULL, '', 'zh', 'general', 'ou', 'or'),
(NULL, '', 'zh', 'general', 'ouvrir', 'Open'),
(NULL, '', 'zh', 'general', 'page', 'page'),
(NULL, '', 'zh', 'general', 'par', 'By'),
(NULL, '', 'zh', 'general', 'params', 'Parameters'),
(NULL, '', 'zh', 'general', 'pasde', 'No '),
(NULL, '', 'zh', 'general', 'pays', 'Country'),
(NULL, '', 'zh', 'general', 'photo', 'Photo'),
(NULL, '', 'zh', 'general', 'photodispo', 'Available Photo'),
(NULL, '', 'zh', 'general', 'position', 'Position'),
(NULL, '', 'zh', 'general', 'pour', 'for'),
(NULL, '', 'zh', 'general', 'pouraccespriv', ' to access protected contents'),
(NULL, '', 'zh', 'general', 'prenom', 'Firstname'),
(NULL, '', 'zh', 'general', 'private', 'private'),
(NULL, '', 'zh', 'general', 'privilege', 'viewing privilege'),
(NULL, '', 'zh', 'general', 'profession', 'Profession'),
(NULL, '', 'zh', 'general', 'profil', 'Profile'),
(NULL, '', 'zh', 'general', 'protected', 'protected'),
(NULL, '', 'zh', 'general', 'please', 'please, '),
(NULL, '', 'zh', 'general', 'pub', 'Publish'),
(NULL, '', 'zh', 'general', 'publish', 'Publish'),
(NULL, '', 'zh', 'general', 'published', 'Published'),
(NULL, '', 'zh', 'general', 'rapport', 'Report'),
(NULL, '', 'zh', 'general', 'repondra', 'will reply'),
(NULL, '', 'zh', 'general', 'reponse', 'Response'),
(NULL, '', 'zh', 'general', 'rechercher', 'Search'),
(NULL, '', 'zh', 'general', 'recopiercode', 'Write the anti-spam code that appears in the image below.'),
(NULL, '', 'zh', 'general', 'redacteur', 'Contributor'),
(NULL, '', 'zh', 'general', 'refuse', 'Denied'),
(NULL, '', 'zh', 'general', 'retour', 'Back'),
(NULL, '', 'zh', 'general', 'rmmbr', 'Remember Me'),
(NULL, '', 'zh', 'general', 'sauf', 'except'),
(NULL, '', 'zh', 'general', 'sauver', 'Save'),
(NULL, '', 'zh', 'general', 'skype', 'Skype'),
(NULL, '', 'zh', 'general', 'sortir', 'Logout'),
(NULL, '', 'zh', 'general', 'statut', 'Status'),
(NULL, '', 'zh', 'general', 'string', 'String'),
(NULL, '', 'zh', 'general', 'sujet', 'Subject'),
(NULL, '', 'zh', 'general', 'sur', '>'),
(NULL, '', 'zh', 'general', 'svnup', 'Update the system with SVN'),
(NULL, '', 'zh', 'general', 'sync', 'Synchronize the site'),
(NULL, '', 'zh', 'general', 'telecharger', 'Download'),
(NULL, '', 'zh', 'general', 'template', 'Template'),
(NULL, '', 'zh', 'general', 'titre', 'Title'),
(NULL, '', 'zh', 'general', 'tout', 'all'),
(NULL, '', 'zh', 'general', 'tplemailaccountcreated', 'Your account has been created on'),
(NULL, '', 'zh', 'general', 'tplemailvisitandlogin', 'Visit us and login with the following credentials:'),
(NULL, '', 'zh', 'general', 'tplemailxtrainfo', 'To access the privileged content, please follow the instructions upon your first login: <b>change the password</b>.<br />Upon each modification of your password, you will have to login again.<br />You may also update your profile page.'),
(NULL, '', 'zh', 'general', 'type', 'Type'),
(NULL, '', 'zh', 'general', 'until', 'Until'),
(NULL, '', 'zh', 'general', 'upldb', 'Upload SQL data to the database'),
(NULL, '', 'zh', 'general', 'url', 'URL'),
(NULL, '', 'zh', 'general', 'versliste', 'to the list'),
(NULL, '', 'zh', 'general', 'ville', 'City'),
(NULL, '', 'zh', 'general', 'voir', 'See'),
(NULL, '', 'zh', 'general', 'vousinscrire', 'Register'),
(NULL, '', 'zh', 'general', 'Y', 'Yes'),
(NULL, '', 'zh', 'gendre', '1', 'Mr &amp; Mrs'),
(NULL, '', 'zh', 'gendre', '2', 'Mrs'),
(NULL, '', 'zh', 'gendre', '3', 'Mr'),
(NULL, '', 'zh', 'gendre', '4', 'Miss'),
(NULL, '', 'zh', 'jour', '1', 'Sunday'),
(NULL, '', 'zh', 'jour', '2', 'Monday'),
(NULL, '', 'zh', 'jour', '3', 'Tuesday'),
(NULL, '', 'zh', 'jour', '4', 'Wednesday'),
(NULL, '', 'zh', 'jour', '5', 'Thursday'),
(NULL, '', 'zh', 'jour', '6', 'Friday'),
(NULL, '', 'zh', 'jour', '7', 'Saturday'),
(NULL, '', 'zh', 'lang', '1', 'Arabic'),
(NULL, '', 'zh', 'lang', '2', 'German'),
(NULL, '', 'zh', 'lang', '3', 'English'),
(NULL, '', 'zh', 'lang', '4', 'Spanish'),
(NULL, '', 'zh', 'lang', '5', 'French'),
(NULL, '', 'zh', 'lang', '6', 'Italian'),
(NULL, '', 'zh', 'lang', '7', 'Japanese'),
(NULL, '', 'zh', 'lang', '8', 'Russian'),
(NULL, '', 'zh', 'lang', '9', 'Chinese'),
(NULL, '', 'zh', 'mois', '1', 'January'),
(NULL, '', 'zh', 'mois', '2', 'February'),
(NULL, '', 'zh', 'mois', '3', 'March'),
(NULL, '', 'zh', 'mois', '4', 'April'),
(NULL, '', 'zh', 'mois', '5', 'May'),
(NULL, '', 'zh', 'mois', '6', 'June'),
(NULL, '', 'zh', 'mois', '7', 'July'),
(NULL, '', 'zh', 'mois', '8', 'August'),
(NULL, '', 'zh', 'mois', '9', 'September'),
(NULL, '', 'zh', 'mois', '10', 'October'),
(NULL, '', 'zh', 'mois', '11', 'November'),
(NULL, '', 'zh', 'mois', '12', 'December'),
(NULL, '', 'zh', 'privilege', '1', 'Public'),
(NULL, '', 'zh', 'privilege', '2', 'Level 2'),
(NULL, '', 'zh', 'privilege', '3', 'Level 3'),
(NULL, '', 'zh', 'privilege', '4', 'Level 4'),
(NULL, '', 'zh', 'statut', 'N', 'On hold'),
(NULL, '', 'zh', 'statut', 'Y', 'Confirmed'),
(NULL, '', 'zh', 'sujet', '1', 'My Next Project'),
(NULL, '', 'zh', 'sujet', '2', 'WebDev'),
(NULL, '', 'zh', 'sujet', '3', 'Web Marketing'),
(NULL, '', 'zh', 'sujet', '4', 'Translation'),
(NULL, '', 'zh', 'sujet', '5', 'Other');