INSERT INTO `_string` (`stringid`, `stringpg`, `stringlang`, `stringtype`, `stringtitle`, `stringentry`) VALUES
(NULL, '', 'it', 'help', 'admin', 'Gli amministratori gestiscono i conti di amministrazione qui. Aggiungere, modificare, cancellare e assegnare privilegi di accesso.'),
(NULL, '', 'it', 'help', 'user', 'Inserire nuovi utenti, modificare o cancellare quegli gi&agrave; esistenti su questo pannello. Soci hanno accesso a moduli simili su loro proprio profilo. Altri moduli possono essere collegati e si pu&ograve; anche aggiungere media o documenti.'),
(NULL, '', 'it', 'help', 'newsletter', 'Inviare una newsletter ai soci registrati e gestire quelli gi&agrave; inviati. Si pu&ograve; anche inviare ad altri email aggiuntivi.'),
(NULL, '', 'it', 'help', 'string', 'Modificare tutte le parole e voci di testo che compaiono sul sito sia nell`area di amministrazione che altrove. Attenzione, certi cambiamenti possono avere risultati strani come ad esempio sui pulsanti di moduli.'),
(NULL, '', 'it', 'help', 'bannedip', 'Elenco di tutti IP vietati registrati dal sistema di blog. Si pu&ograve; pure aggiungere alcuni direttamente l&igrave;.'),
(NULL, '', 'it', 'help', 'communications', 'Questa sezione offre un modulo simile a quello per contattarci eccetto il fato che si pu&ograve; scegliere gruppi a chi inviare. Soci possono anche avere accesso a questo modulo.'),
(NULL, '', 'it', 'help', 'media', 'Tutti i file media come foto, video, documenti o altri sono gestibili qui o dentro ogni moduli specifici e nelle pagine.'),
(NULL, '', 'it', 'help', 'event', 'Creare nuovi eventi, modificare o cancellare quelli esistenti.'),
(NULL, '', 'it', 'help', 'gallery', 'Creare nuove gallerie foto, modificare o cancellare quelli esistenti. Per inviare una galleria intera, si pu&ograve; fare velocemente con un zip invece di inviare una alla volta.'),
(NULL, '', 'it', 'help', 'forum', 'Gestire o cancellare i contenuti registrati dagli utenti. Si scelga anche di mettere gli indirizzi indesiderati nel bannedips.'),
(NULL, '', 'it', 'general', 'achoisir', 'da Scegliere'),
(NULL, '', 'it', 'general', 'acceder', 'Accedere'),
(NULL, '', 'it', 'general', 'acces', 'Accesso'),
(NULL, '', 'it', 'general', 'accordusage', 'Cliccando qui si accetta di ricevere la newsletter (Gli Email inseriti non vengano mai ne pubblicati ne venduti!)'),
(NULL, '', 'it', 'general', 'accueil', 'Homepage'),
(NULL, '', 'it', 'general', 'admin', 'Amministratore'),
(NULL, '', 'it', 'general', 'admincheckconf', 'L&acute;amministrazione ha ricevuto la vostra richiesta di inserrimento e verr&aacute; confermata fra 24 ore tramite mail. Grazie!'),
(NULL, '', 'it', 'general', 'adresse', 'Indirizzo'),
(NULL, '', 'it', 'general', 'adressecomp', 'Indirizzo completo'),
(NULL, '', 'it', 'general', 'aenvoyer', 'da inviare'),
(NULL, '', 'it', 'general', 'aide', 'Aiuto'),
(NULL, '', 'it', 'general', 'ajout', 'Nuovo'),
(NULL, '', 'it', 'general', 'ajouter', 'Aggiungere'),
(NULL, '', 'it', 'general', 'analytics', 'Analytics'),
(NULL, '', 'it', 'general', 'anonyme', 'Anonimo'),
(NULL, '', 'it', 'general', 'archive', 'Archivio'),
(NULL, '', 'it', 'general', 'archived', 'Archiviato'),
(NULL, '', 'it', 'general', 'ASC', 'Crescendo'),
(NULL, '', 'it', 'general', 'aujourdhui', 'oggi'),
(NULL, '', 'it', 'general', 'batch', 'Invio di gruppo'),
(NULL, '', 'it', 'general', 'bakdb', 'Fare un backup del database'),
(NULL, '', 'it', 'general', 'bannedip', 'IP vietati'),
(NULL, '', 'it', 'general', 'bientot', 'presto'),
(NULL, '', 'it', 'general', 'bienvenue', 'Benvenuto'),
(NULL, '', 'it', 'general', 'bloginfo', 'blog info'),
(NULL, '', 'it', 'general', 'calendrier', 'calendario'),
(NULL, '', 'it', 'general', 'cettepage', 'questa pagina'),
(NULL, '', 'it', 'general', 'changer', 'Cambiare'),
(NULL, '', 'it', 'general', 'cher', 'Caro'),
(NULL, '', 'it', 'general', 'choisir', 'Scegliere'),
(NULL, '', 'it', 'general', 'cliquerici', 'Cliccare qui'),
(NULL, '', 'it', 'general', 'code', 'codice'),
(NULL, '', 'it', 'general', 'codpost', 'CAP'),
(NULL, '', 'it', 'general', 'compagnie', 'Azienda'),
(NULL, '', 'it', 'general', 'comment', 'Commento'),
(NULL, '', 'it', 'general', 'comments', 'Commenti'),
(NULL, '', 'it', 'general', 'communications', 'comunicazioni'),
(NULL, '', 'it', 'general', 'config', 'Config'),
(NULL, '', 'it', 'general', 'confinfo', 'conf info'),
(NULL, '', 'it', 'general', 'confirmation', 'Conferma'),
(NULL, '', 'it', 'general', 'confirmationeffacement', 'Sicuro di voler cancellare?'),
(NULL, '', 'it', 'general', 'confirme', 'confermato'),
(NULL, '', 'it', 'general', 'confirmer', 'Confermare'),
(NULL, '', 'it', 'general', 'coords', 'Coordinati'),
(NULL, '', 'it', 'general', 'copyrightnotice', 'Webdevelopment da <a href=http://www.mediavince.com target=_blank>Media Vince</a> &copy; '),
(NULL, '', 'it', 'general', 'credentials', 'Credenziali'),
(NULL, '', 'it', 'general', 'date', 'Data di pubblicazione'),
(NULL, '', 'it', 'general', 'datecree', 'Data di creazione'),
(NULL, '', 'it', 'general', 'datenaissance', 'Data di nascit&agrave;'),
(NULL, '', 'it', 'general', 'de', 'di'),
(NULL, '', 'it', 'general', 'deja', 'gi&agrave;'),
(NULL, '', 'it', 'general', 'dejaexistant', 'gi&agrave; esistente'),
(NULL, '', 'it', 'general', 'derequete', 'di richiesta'),
(NULL, '', 'it', 'general', 'dernier', 'Ultimo'),
(NULL, '', 'it', 'general', 'derniere', 'Ultima'),
(NULL, '', 'it', 'general', 'DESC', 'Scendendo'),
(NULL, '', 'it', 'general', 'description', 'Descrizione'),
(NULL, '', 'it', 'general', 'destinataire', 'inviato a'),
(NULL, '', 'it', 'general', 'detexte', 'di testo'),
(NULL, '', 'it', 'general', 'dispo', 'disponibile'),
(NULL, '', 'it', 'general', 'doc', 'documento'),
(NULL, '', 'it', 'general', 'docdispo', 'documenti disponibili'),
(NULL, '', 'it', 'general', 'efface', 'cancellato'),
(NULL, '', 'it', 'general', 'effacer', 'Cancellare'),
(NULL, '', 'it', 'general', 'effectue', 'effettuato'),
(NULL, '', 'it', 'general', 'email', 'Email'),
(NULL, '', 'it', 'general', 'enattente', 'in attesa'),
(NULL, '', 'it', 'general', 'enregistre', 'registrato'),
(NULL, '', 'it', 'general', 'enregistrement', 'Registrazione'),
(NULL, '', 'it', 'general', 'erreur', 'Errore'),
(NULL, '', 'it', 'general', 'entrer', 'Login'),
(NULL, '', 'it', 'general', 'envoidoc', 'Caricare il Documento'),
(NULL, '', 'it', 'general', 'envoiphoto', 'Caricare il Media'),
(NULL, '', 'it', 'general', 'envoye', 'inviato'),
(NULL, '', 'it', 'general', 'envoyer', 'Inviare'),
(NULL, '', 'it', 'general', 'event', 'Evento'),
(NULL, '', 'it', 'general', 'existant', 'esistente'),
(NULL, '', 'it', 'general', 'fichier', 'File'),
(NULL, '', 'it', 'general', 'forgotpass', 'Mi sono dimenticato la password'),
(NULL, '', 'it', 'general', 'forgotpasshelp', '<b>Procedere cos&igrave;:</b><br />> Indicare il Nome Utente<br />> Selezionare la casella<br />> Cliccare per entrare<br />Una nuova password sar&agrave; inoltrata verso l`email corrispondente!'),
(NULL, '', 'it', 'general', 'forum', 'Forum'),
(NULL, '', 'it', 'general', 'from', 'Da'),
(NULL, '', 'it', 'general', 'gallery', 'Galleria'),
(NULL, '', 'it', 'general', 'gendre', 'Stato Civile'),
(NULL, '', 'it', 'general', 'gestion', 'Gestione'),
(NULL, '', 'it', 'general', 'heure', 'ora'),
(NULL, '', 'it', 'general', 'identifierencore', 'Fare il login ancora per favore.'),
(NULL, '', 'it', 'general', 'img', 'Imagine'),
(NULL, '', 'it', 'general', 'infodb', 'Info DB'),
(NULL, '', 'it', 'general', 'invalide', 'invalido'),
(NULL, '', 'it', 'general', 'jour', 'Giorno'),
(NULL, '', 'it', 'general', 'laisservidepourgarder', 'Lasciare vuoto per mantenerlo'),
(NULL, '', 'it', 'general', 'langue', 'Linguaggio'),
(NULL, '', 'it', 'general', 'lesautrespages', 'le altre pagine'),
(NULL, '', 'it', 'general', 'listecorrection', 'Per favore verificare le voce in rosso!'),
(NULL, '', 'it', 'general', 'logo', 'Logo'),
(NULL, '', 'it', 'general', 'manquant', 'mancante'),
(NULL, '', 'it', 'general', 'map', 'mappa'),
(NULL, '', 'it', 'general', 'marketing1', 'Maggiori informazioni su di me'),
(NULL, '', 'it', 'general', 'max', 'Maximum'),
(NULL, '', 'it', 'general', 'media', 'Media'),
(NULL, '', 'it', 'general', 'membre', 'Socio'),
(NULL, '', 'it', 'general', 'menu', 'men&ugrave;'),
(NULL, '', 'it', 'general', 'metadesc', 'Descrizione per meta'),
(NULL, '', 'it', 'general', 'metakeyw', 'Parole chiave'),
(NULL, '', 'it', 'general', 'mettreenattente', 'Mettere in attesa'),
(NULL, '', 'it', 'general', 'message', 'Messaggio'),
(NULL, '', 'it', 'general', 'min', 'Minimum'),
(NULL, '', 'it', 'general', 'moderateurverif', '(Il forum e i commenti sono moderati e verranno pubblicati solo a seguito della approvazione dell`amministratore del sito)'),
(NULL, '', 'it', 'general', 'modification', 'Modifica'),
(NULL, '', 'it', 'general', 'modifie', 'modificato'),
(NULL, '', 'it', 'general', 'modifier', 'Modificare'),
(NULL, '', 'it', 'general', 'module', 'Modulo'),
(NULL, '', 'it', 'general', 'mois', 'mese'),
(NULL, '', 'it', 'general', 'motdepasse', 'Password'),
(NULL, '', 'it', 'general', 'multimedia', 'Multimedia'),
(NULL, '', 'it', 'general', 'N', 'No'),
(NULL, '', 'it', 'general', 'name', 'Cognome'),
(NULL, '', 'it', 'general', 'newsletter', 'Newsletter'),
(NULL, '', 'it', 'general', 'nl_adhesionprete', 'La vostra registrazione &egrave; pronta.<br /> <br />Sotto, si trovano i vostri credenziali per accedere a vostro profilo e all`area protetta del sito.'),
(NULL, '', 'it', 'general', 'nl_copiercoller', 'Per favore cliccare o copiare e incollare il collegamento in una nuova finestra'),
(NULL, '', 'it', 'general', 'nl_liresursite', 'Per leggere queta pagine su'),
(NULL, '', 'it', 'general', 'nl_messagepreview', 'Ecco quello che ogni soci registrati riceverano'),
(NULL, '', 'it', 'general', 'nl_sepadressesemail', '(separare ogni email con una virgola e uno spazio cos&igrave;: &acute;, &acute;)'),
(NULL, '', 'it', 'general', 'nom', 'Cognome'),
(NULL, '', 'it', 'general', 'nomutil', 'Nome utente'),
(NULL, '', 'it', 'general', 'non', 'NON'),
(NULL, '', 'it', 'general', 'nouveau', 'nuovo'),
(NULL, '', 'it', 'general', 'nouveaumdpachanger', 'Una nuova password &egrave; stata inoltrata tramite email, grazie di modificarla nella prossima visita!'),
(NULL, '', 'it', 'general', 'nphoto', 'Numero di Foto'),
(NULL, '', 'it', 'general', 'num', 'Numero'),
(NULL, '', 'it', 'general', 'numfax', 'Numero di FAX'),
(NULL, '', 'it', 'general', 'numid', 'Numero ID'),
(NULL, '', 'it', 'general', 'numtel', 'Recapito di telefono'),
(NULL, '', 'it', 'general', 'obligatoire', 'obbligatorio'),
(NULL, '', 'it', 'general', 'optdb', 'Ottimizzare il database'),
(NULL, '', 'it', 'general', 'options', 'Opzione'),
(NULL, '', 'it', 'general', 'ordre', 'Ordine'),
(NULL, '', 'it', 'general', 'organisation', 'Organizzazione'),
(NULL, '', 'it', 'general', 'ou', 'o'),
(NULL, '', 'it', 'general', 'ouvrir', 'Aprire'),
(NULL, '', 'it', 'general', 'page', 'pagine'),
(NULL, '', 'it', 'general', 'par', 'da'),
(NULL, '', 'it', 'general', 'params', 'Parametri'),
(NULL, '', 'it', 'general', 'pasde', 'Nessun '),
(NULL, '', 'it', 'general', 'pays', 'Paese'),
(NULL, '', 'it', 'general', 'photo', 'Foto'),
(NULL, '', 'it', 'general', 'photodispo', 'Foto disponibile'),
(NULL, '', 'it', 'general', 'position', 'Posizione'),
(NULL, '', 'it', 'general', 'pour', 'per'),
(NULL, '', 'it', 'general', 'pouraccespriv', ' per accedere ai contenuti protetti'),
(NULL, '', 'it', 'general', 'prenom', 'Nome'),
(NULL, '', 'it', 'general', 'private', 'privato'),
(NULL, '', 'it', 'general', 'privilege', 'privileggio'),
(NULL, '', 'it', 'general', 'profession', 'Professione'),
(NULL, '', 'it', 'general', 'profil', 'Profilo'),
(NULL, '', 'it', 'general', 'protected', 'protetto'),
(NULL, '', 'it', 'general', 'please', 'per favore, '),
(NULL, '', 'it', 'general', 'pub', 'Pubblicare'),
(NULL, '', 'it', 'general', 'publish', 'Pubblicare'),
(NULL, '', 'it', 'general', 'published', 'Pubblicato'),
(NULL, '', 'it', 'general', 'rapport', 'Rapporto'),
(NULL, '', 'it', 'general', 'repondra', 'risponder&agrave;'),
(NULL, '', 'it', 'general', 'reponse', 'Risposta'),
(NULL, '', 'it', 'general', 'rechercher', 'Ricerca'),
(NULL, '', 'it', 'general', 'recopiercode', 'Scrivere il codice anti-spam cos&igrave; come apparisce nell`imagine sotto.'),
(NULL, '', 'it', 'general', 'redacteur', 'Autore'),
(NULL, '', 'it', 'general', 'refuse', 'negato'),
(NULL, '', 'it', 'general', 'retour', 'Indietro'),
(NULL, '', 'it', 'general', 'rmmbr', 'Riccordarmi'),
(NULL, '', 'it', 'general', 'sauf', 'eccetto'),
(NULL, '', 'it', 'general', 'sauver', 'Salvare'),
(NULL, '', 'it', 'general', 'skype', 'Skype'),
(NULL, '', 'it', 'general', 'sortir', 'Uscire'),
(NULL, '', 'it', 'general', 'statut', 'Stato'),
(NULL, '', 'it', 'general', 'string', 'Voci'),
(NULL, '', 'it', 'general', 'sujet', 'Oggetto'),
(NULL, '', 'it', 'general', 'sur', 'su'),
(NULL, '', 'it', 'general', 'svnup', 'Aggiornare il sistema con SVN'),
(NULL, '', 'it', 'general', 'sync', 'Sincronizzare il sito'),
(NULL, '', 'it', 'general', 'telecharger', 'Scaricare'),
(NULL, '', 'it', 'general', 'template', 'Modello'),
(NULL, '', 'it', 'general', 'tplemailaccountcreated', 'Il vostro conto &egrave; stato creato su'),
(NULL, '', 'it', 'general', 'tplemailvisitandlogin', 'Digitate il nostro sito e impostate i parametri per il login di seguito riportati:'),
(NULL, '', 'it', 'general', 'tplemailxtrainfo', 'Per accedere ai contenuti protteti &egrave; necessario eseguire il <b>cambiamento della password al primo accesso</b>.<br />Poi, ogni volta che si cambia la password verr&agrave; eseguito il logout.<br />Sar&agrave; possibile modificare i propri dati sulla pagina personale.'),
(NULL, '', 'it', 'general', 'titre', 'Titolo'),
(NULL, '', 'it', 'general', 'tout', 'tutto'),
(NULL, '', 'it', 'general', 'type', 'Tipo'),
(NULL, '', 'it', 'general', 'until', 'Fino a'),
(NULL, '', 'it', 'general', 'upldb', 'Inviare SQL nel database'),
(NULL, '', 'it', 'general', 'url', 'URL'),
(NULL, '', 'it', 'general', 'versliste', 'verso l`elenco'),
(NULL, '', 'it', 'general', 'ville', 'Citt&agrave;'),
(NULL, '', 'it', 'general', 'voir', 'Vedere'),
(NULL, '', 'it', 'general', 'vousinscrire', 'Registrarsi'),
(NULL, '', 'it', 'general', 'Y', 'S&igrave;'),
(NULL, '', 'it', 'gendre', '1', 'Signore e Signora'),
(NULL, '', 'it', 'gendre', '2', 'Signora'),
(NULL, '', 'it', 'gendre', '3', 'Signore'),
(NULL, '', 'it', 'gendre', '4', 'Signorina'),
(NULL, '', 'it', 'jour', '1', 'Domenica'),
(NULL, '', 'it', 'jour', '2', 'Luned&igrave;'),
(NULL, '', 'it', 'jour', '3', 'Marted&igrave;'),
(NULL, '', 'it', 'jour', '4', 'Mercoled&igrave;'),
(NULL, '', 'it', 'jour', '5', 'Gioved&igrave;'),
(NULL, '', 'it', 'jour', '6', 'Venerd&igrave;'),
(NULL, '', 'it', 'jour', '7', 'Sabato'),
(NULL, '', 'it', 'lang', 'ar', 'Arabo'),
(NULL, '', 'it', 'lang', 'de', 'Tedesco'),
(NULL, '', 'it', 'lang', 'en', 'Inglese'),
(NULL, '', 'it', 'lang', 'sp', 'Spaniolo'),
(NULL, '', 'it', 'lang', 'fi', 'Finlandese'),
(NULL, '', 'it', 'lang', 'fr', 'Francese'),
(NULL, '', 'it', 'lang', 'it', 'Italiano'),
(NULL, '', 'it', 'lang', 'jp', 'Giapponese'),
(NULL, '', 'it', 'lang', 'no', 'Norvegese'),
(NULL, '', 'it', 'lang', 'ru', 'Russo'),
(NULL, '', 'it', 'lang', 'zh', 'Cinese'),
(NULL, '', 'it', 'mois', '1', 'Gennaio'),
(NULL, '', 'it', 'mois', '2', 'Febbraio'),
(NULL, '', 'it', 'mois', '3', 'Marzo'),
(NULL, '', 'it', 'mois', '4', 'Aprile'),
(NULL, '', 'it', 'mois', '5', 'Maggio'),
(NULL, '', 'it', 'mois', '6', 'Giugnio'),
(NULL, '', 'it', 'mois', '7', 'Luglio'),
(NULL, '', 'it', 'mois', '8', 'Agosto'),
(NULL, '', 'it', 'mois', '9', 'Settembre'),
(NULL, '', 'it', 'mois', '10', 'Ottobre'),
(NULL, '', 'it', 'mois', '11', 'Novembre'),
(NULL, '', 'it', 'mois', '12', 'Dicembre'),
(NULL, '', 'it', 'privilege', '1', 'Pubblico'),
(NULL, '', 'it', 'privilege', '2', 'Livello 2'),
(NULL, '', 'it', 'privilege', '3', 'Livello 3'),
(NULL, '', 'it', 'privilege', '4', 'Livello 4'),
(NULL, '', 'it', 'statut', 'N', 'In attesa'),
(NULL, '', 'it', 'statut', 'Y', 'Confermato'),
(NULL, '', 'it', 'sujet', '1', 'Il mio prossimo progetto'),
(NULL, '', 'it', 'sujet', '2', 'Sviluppo sul Web'),
(NULL, '', 'it', 'sujet', '3', 'Marketing sul Web'),
(NULL, '', 'it', 'sujet', '4', 'Traduzione'),
(NULL, '', 'it', 'sujet', '5', 'Altro');