INSERT INTO `_string` (`stringid`, `stringpg`, `stringlang`, `stringtype`, `stringtitle`, `stringentry`) VALUES
(NULL, '', 'fr', 'help', 'admin', 'Les comptes d`administration sont g&eacute;r&eacute;s dans cette section. On peut aussi distribuer des privil&egrave;ges.'),
(NULL, '', 'fr', 'help', 'user', 'Cr&eacute;er des utilisateurs ou modifier et effacer des comptes d&eacute;j&agrave; existants. Les membres ont acc&egrave;s &agrave; leur profil.'),
(NULL, '', 'fr', 'help', 'newsletter', 'Envoi de newsletter aux membres et gestion. Il est aussi possible d`en r&eacute;-envoyer.'),
(NULL, '', 'fr', 'help', 'string', 'Edition des textes fixes utilis&eacute;s en admin et autre. Attention, certains changements peuvent avoir des r&eacute;percussions sur l`int&eacute;grit&eacute; du syst&egrave;me.'),
(NULL, '', 'fr', 'help', 'bannedip', 'Liste de toutes les IPs qui ont &eacute;t&eacute; bloqu&eacute;es. On peut en ins&eacute;rer aussi i&ccedil;i.'),
(NULL, '', 'fr', 'help', 'communications', 'Cette section permet de remplir un formulaire tel que celui de la page de contact avec de plus la possiblit&eacute; de l`envoyer &agrave; des groupes de personnes. Les membres peuvent avoir acc&egrave;s &agrave; ces formes.'),
(NULL, '', 'fr', 'help', 'media', 'C`est i&ccedil;i que sont r&eacute;pertori&eacute;s tous les documents et fichiers m&eacute;dias. On peut aussi en g&eacute;rer sur certains modules.'),
(NULL, '', 'fr', 'help', 'event', 'Cr&eacute;er des &eacute;v&egrave;nements ou modifier et effacer ceux d&eacute;j&agrave; existants.'),
(NULL, '', 'fr', 'help', 'gallery', 'Cr&eacute;er des galeries ou modifier et effacer celles d&eacute;j&agrave; existantes. Il est possible d`utiliser la function ZIP pour envoyer des galeries enti&egrave;res.'),
(NULL, '', 'fr', 'help', 'forum', 'Gestion des messages &eacute;chang&eacute;s sur le forum. c`est aussi i&ccedil;i que l`on peut bannir des IPs.'),
(NULL, '', 'fr', 'general', 'achoisir', '&agrave; choisir'),
(NULL, '', 'fr', 'general', 'acceder', 'Acc&egrave;der'),
(NULL, '', 'fr', 'general', 'acces', 'Acc&egrave;s'),
(NULL, '', 'fr', 'general', 'accordusage', 'En cliquant, vous acceptez de recevoir la newsletter (Les adresses Email soumises ne seront ni publi&eacute;es ni vendues !)'),
(NULL, '', 'fr', 'general', 'accueil', 'Homepage'),
(NULL, '', 'fr', 'general', 'admin', 'Admin'),
(NULL, '', 'fr', 'general', 'admincheckconf', 'L&acute;administration a re&ccedil;u votre demande d&acute;inscription et vous confirmera dans environ 24 heures par email votre adh&eacute;sion. Merci!'),
(NULL, '', 'fr', 'general', 'adresse', 'Adresse'),
(NULL, '', 'fr', 'general', 'adressecomp', 'Adresse compl&egrave;te'),
(NULL, '', 'fr', 'general', 'aenvoyer', '&agrave; envoyer'),
(NULL, '', 'fr', 'general', 'aide', 'Aide'),
(NULL, '', 'fr', 'general', 'ajout', 'Ajout'),
(NULL, '', 'fr', 'general', 'ajouter', 'Ajouter'),
(NULL, '', 'fr', 'general', 'analytics', 'Analytics'),
(NULL, '', 'fr', 'general', 'anonyme', 'Anonyme'),
(NULL, '', 'fr', 'general', 'archive', 'Archive'),
(NULL, '', 'fr', 'general', 'archived', 'Archiv&eacute;'),
(NULL, '', 'fr', 'general', 'ASC', 'Croissant'),
(NULL, '', 'fr', 'general', 'aujourdhui', 'ajourd`hui'),
(NULL, '', 'fr', 'general', 'batch', 'Envoi group&eacute;'),
(NULL, '', 'fr', 'general', 'bakdb', 'Faire une sauvegarde de la base de donn&eacute;es'),
(NULL, '', 'fr', 'general', 'bannedip', 'IPs bannies'),
(NULL, '', 'fr', 'general', 'bientot', 'bient&ocirc;t'),
(NULL, '', 'fr', 'general', 'bienvenue', 'Bienvenue'),
(NULL, '', 'fr', 'general', 'bloginfo', 'blog info'),
(NULL, '', 'fr', 'general', 'calendrier', 'calendrier'),
(NULL, '', 'fr', 'general', 'cettepage', 'cette page'),
(NULL, '', 'fr', 'general', 'changer', 'Changer'),
(NULL, '', 'fr', 'general', 'cher', 'Cher'),
(NULL, '', 'fr', 'general', 'choisir', 'Choisir'),
(NULL, '', 'fr', 'general', 'cliquerici', 'Cliquer i&ccedil;i'),
(NULL, '', 'fr', 'general', 'code', 'code'),
(NULL, '', 'fr', 'general', 'codpost', 'Code Postal'),
(NULL, '', 'fr', 'general', 'compagnie', 'Compagnie'),
(NULL, '', 'fr', 'general', 'comment', 'Comment'),
(NULL, '', 'fr', 'general', 'comments', 'Commentaire'),
(NULL, '', 'fr', 'general', 'communications', 'Communications'),
(NULL, '', 'fr', 'general', 'config', 'Config'),
(NULL, '', 'fr', 'general', 'confinfo', 'conf info'),
(NULL, '', 'fr', 'general', 'confirmation', 'Confirmation'),
(NULL, '', 'fr', 'general', 'confirmationeffacement', 'Etes vous s&ucirc;r de vouloir effacer ?'),
(NULL, '', 'fr', 'general', 'confirme', 'confirm&eacute;'),
(NULL, '', 'fr', 'general', 'confirmer', 'Confirmer'),
(NULL, '', 'fr', 'general', 'coords', 'Coordonn&eacute;es'),
(NULL, '', 'fr', 'general', 'copyrightnotice', 'D&eacute;veloppement WEB par <a href=http://www.mediavince.com target=_blank>Media Vince</a> &copy; '),
(NULL, '', 'fr', 'general', 'credentials', 'Modalit&eacute;s d`acc&egrave;s'),
(NULL, '', 'fr', 'general', 'date', 'Date post&eacute;'),
(NULL, '', 'fr', 'general', 'datecree', 'Date cr&eacute;&eacute;'),
(NULL, '', 'fr', 'general', 'datenaissance', 'Date de naissance'),
(NULL, '', 'fr', 'general', 'de', 'de'),
(NULL, '', 'fr', 'general', 'deja', 'd&eacute;j&agrave;'),
(NULL, '', 'fr', 'general', 'dejaexistant', 'd&eacute;j&agrave; existant'),
(NULL, '', 'fr', 'general', 'derequete', 'de requ&ecirc;te'),
(NULL, '', 'fr', 'general', 'dernier', 'Dernier'),
(NULL, '', 'fr', 'general', 'derniere', 'Derni&egrave;re'),
(NULL, '', 'fr', 'general', 'DESC', 'D&eacute;croissant'),
(NULL, '', 'fr', 'general', 'description', 'Description'),
(NULL, '', 'fr', 'general', 'destinataire', 'destinataire'),
(NULL, '', 'fr', 'general', 'detexte', 'de texte'),
(NULL, '', 'fr', 'general', 'dispo', 'disponible'),
(NULL, '', 'fr', 'general', 'doc', 'document'),
(NULL, '', 'fr', 'general', 'docdispo', 'Documents disponibles'),
(NULL, '', 'fr', 'general', 'efface', 'effac&eacute;'),
(NULL, '', 'fr', 'general', 'effacer', 'effacer'),
(NULL, '', 'fr', 'general', 'effectue', 'effectu&eacute;'),
(NULL, '', 'fr', 'general', 'email', 'Email'),
(NULL, '', 'fr', 'general', 'enattente', 'en attente'),
(NULL, '', 'fr', 'general', 'enregistre', 'enregistr&eacute;'),
(NULL, '', 'fr', 'general', 'enregistrement', 'Enregistrement'),
(NULL, '', 'fr', 'general', 'erreur', 'Erreur'),
(NULL, '', 'fr', 'general', 'entrer', 'Entrer'),
(NULL, '', 'fr', 'general', 'envoidoc', 'Envoi du document'),
(NULL, '', 'fr', 'general', 'envoiphoto', 'Envoi du m&eacute;dia'),
(NULL, '', 'fr', 'general', 'envoye', 'envoy&eacute;'),
(NULL, '', 'fr', 'general', 'envoyer', 'Envoyer'),
(NULL, '', 'fr', 'general', 'event', 'Ev&egrave;nement'),
(NULL, '', 'fr', 'general', 'existant', 'existant'),
(NULL, '', 'fr', 'general', 'fichier', 'Fichier'),
(NULL, '', 'fr', 'general', 'forgotpass', 'J`ai oubli&eacute; mon mot de passe'),
(NULL, '', 'fr', 'general', 'forgotpasshelp', '<b>Suivre ces instructions:</b><br />> Entrer le Nom d`Util<br />> Cocher cette case<br />> Cliquer pour entrer<br />Un nouveau mot de passe sera envoy&eacute; &agrave; l`adresse correspondante!'),
(NULL, '', 'fr', 'general', 'forum', 'Forum'),
(NULL, '', 'fr', 'general', 'from', 'De'),
(NULL, '', 'fr', 'general', 'gallery', 'Galerie'),
(NULL, '', 'fr', 'general', 'gendre', 'Civilil&eacute;'),
(NULL, '', 'fr', 'general', 'gestion', 'Gestion'),
(NULL, '', 'fr', 'general', 'heure', 'heure'),
(NULL, '', 'fr', 'general', 'identifierencore', 'Merci de vous identifier de nouveau.'),
(NULL, '', 'fr', 'general', 'img', 'Image'),
(NULL, '', 'fr', 'general', 'infodb', 'Infos DB'),
(NULL, '', 'fr', 'general', 'invalide', 'invalide'),
(NULL, '', 'fr', 'general', 'jour', 'Jour'),
(NULL, '', 'fr', 'general', 'laisservidepourgarder', 'Laisser vide pour le garder'),
(NULL, '', 'fr', 'general', 'langue', 'Language'),
(NULL, '', 'fr', 'general', 'lesautrespages', 'les autres pages'),
(NULL, '', 'fr', 'general', 'listecorrection', 'Veuillez corriger ce qui est list&eacute; en rouge!'),
(NULL, '', 'fr', 'general', 'logo', 'Logo'),
(NULL, '', 'fr', 'general', 'manquant', 'manquant'),
(NULL, '', 'fr', 'general', 'map', 'carte'),
(NULL, '', 'fr', 'general', 'marketing1', 'Plus d`informations sur moi'),
(NULL, '', 'fr', 'general', 'max', 'Maximum'),
(NULL, '', 'fr', 'general', 'media', 'M&eacute;dia'),
(NULL, '', 'fr', 'general', 'membre', 'Membre'),
(NULL, '', 'fr', 'general', 'menu', 'menu'),
(NULL, '', 'fr', 'general', 'metadesc', 'Description META'),
(NULL, '', 'fr', 'general', 'metakeyw', 'Mots clefs'),
(NULL, '', 'fr', 'general', 'mettreenattente', 'Mettre en attente'),
(NULL, '', 'fr', 'general', 'message', 'Message'),
(NULL, '', 'fr', 'general', 'min', 'Minimum'),
(NULL, '', 'fr', 'general', 'moderateurverif', '(Le Forum et les commentaires sont mod&eacute;r&eacute;s et n`appara&icirc;trons sur le site qu`apr&egrave;s v&eacute;rification)'),
(NULL, '', 'fr', 'general', 'modification', 'Modification'),
(NULL, '', 'fr', 'general', 'modifie', 'modifi&eacute;'),
(NULL, '', 'fr', 'general', 'modifier', 'Modifier'),
(NULL, '', 'fr', 'general', 'module', 'Module'),
(NULL, '', 'fr', 'general', 'mois', 'mois'),
(NULL, '', 'fr', 'general', 'motdepasse', 'Mot de passe'),
(NULL, '', 'fr', 'general', 'multimedia', 'Multim&eacute;dia'),
(NULL, '', 'fr', 'general', 'N', 'Non'),
(NULL, '', 'fr', 'general', 'name', 'Nom'),
(NULL, '', 'fr', 'general', 'newsletter', 'Newsletter'),
(NULL, '', 'fr', 'general', 'nl_adhesionprete', 'Votre adh&eacute;sion est pr&ecirc;te.<br /> <br />Veuillez trouver ci-dessous les modalit&eacute;s d`acc&egrave;s &agrave; votre compte.'),
(NULL, '', 'fr', 'general', 'nl_copiercoller', 'Merci de copier et coller ce lien dans une nouvelle fen&ecirc;tre'),
(NULL, '', 'fr', 'general', 'nl_liresursite', 'Afin de lire cette page sur '),
(NULL, '', 'fr', 'general', 'nl_messagepreview', 'Voici ce que chacun recevra'),
(NULL, '', 'fr', 'general', 'nl_sepadressesemail', '(s&eacute;parer chaque adresse email par une virgule et un espace : &acute;, &acute;)'),
(NULL, '', 'fr', 'general', 'nom', 'Nom'),
(NULL, '', 'fr', 'general', 'nomutil', 'Nom d`util'),
(NULL, '', 'fr', 'general', 'non', 'NON'),
(NULL, '', 'fr', 'general', 'nouveau', 'nouveau'),
(NULL, '', 'fr', 'general', 'nouveaumdpachanger', 'Un nouveau mot de passe vous a &eactue;t&eacute; envoy&eacute; par email, merci de le modifier au cours de votre prochaine visite!'),
(NULL, '', 'fr', 'general', 'nphoto', 'Nombre de Photos'),
(NULL, '', 'fr', 'general', 'num', 'Num&eacute;ro'),
(NULL, '', 'fr', 'general', 'numfax', 'Num&eacute;ro de FAX'),
(NULL, '', 'fr', 'general', 'numid', 'Num&eacute;ro d`ID'),
(NULL, '', 'fr', 'general', 'numtel', 'Num&eacute;ro de t&eacute;l&eacute;phone'),
(NULL, '', 'fr', 'general', 'obligatoire', 'obligatoire'),
(NULL, '', 'fr', 'general', 'optdb', 'Optimiser la base de donn&eacute;es'),
(NULL, '', 'fr', 'general', 'options', 'Options'),
(NULL, '', 'fr', 'general', 'ordre', 'Ordre'),
(NULL, '', 'fr', 'general', 'organisation', 'Organisation'),
(NULL, '', 'fr', 'general', 'ou', 'ou'),
(NULL, '', 'fr', 'general', 'ouvrir', 'Ouvrir'),
(NULL, '', 'fr', 'general', 'page', 'page'),
(NULL, '', 'fr', 'general', 'par', 'par'),
(NULL, '', 'fr', 'general', 'params', 'Param&ecirc;tres'),
(NULL, '', 'fr', 'general', 'pasde', 'Pas de '),
(NULL, '', 'fr', 'general', 'pays', 'Pays'),
(NULL, '', 'fr', 'general', 'photo', 'Photo'),
(NULL, '', 'fr', 'general', 'photodispo', 'Photos diponibles'),
(NULL, '', 'fr', 'general', 'position', 'Position'),
(NULL, '', 'fr', 'general', 'pour', 'pour'),
(NULL, '', 'fr', 'general', 'pouraccespriv', ' pour acc&eacute;der au contenu'),
(NULL, '', 'fr', 'general', 'prenom', 'Pr&eacute;nom'),
(NULL, '', 'fr', 'general', 'private', 'priv&eacute;'),
(NULL, '', 'fr', 'general', 'privilege', 'privil&egrave;ge'),
(NULL, '', 'fr', 'general', 'profession', 'Profession'),
(NULL, '', 'fr', 'general', 'profil', 'Profil'),
(NULL, '', 'fr', 'general', 'protected', 'prot&eacute;g&eacute;'),
(NULL, '', 'fr', 'general', 'please', 's`il vous plait, '),
(NULL, '', 'fr', 'general', 'pub', 'Publier'),
(NULL, '', 'fr', 'general', 'publish', 'Publier'),
(NULL, '', 'fr', 'general', 'published', 'Publi&eacute;'),
(NULL, '', 'fr', 'general', 'rapport', 'Rapport'),
(NULL, '', 'fr', 'general', 'repondra', 'r&eacute;pondra'),
(NULL, '', 'fr', 'general', 'reponse', 'R&eacute;ponse'),
(NULL, '', 'fr', 'general', 'rechercher', 'Rechercher'),
(NULL, '', 'fr', 'general', 'recopiercode', 'Inscrire le code anti-spam qui appara&icirc;t dans l`image.'),
(NULL, '', 'fr', 'general', 'redacteur', 'R&eacute;dacteur'),
(NULL, '', 'fr', 'general', 'refuse', 'Refus&eacute;'),
(NULL, '', 'fr', 'general', 'retour', 'Retour'),
(NULL, '', 'fr', 'general', 'rmmbr', 'Me m&eacute;moriser'),
(NULL, '', 'fr', 'general', 'sauf', 'sauf'),
(NULL, '', 'fr', 'general', 'sauver', 'Sauver'),
(NULL, '', 'fr', 'general', 'skype', 'Skype'),
(NULL, '', 'fr', 'general', 'sortir', 'Sortir'),
(NULL, '', 'fr', 'general', 'statut', 'Statut'),
(NULL, '', 'fr', 'general', 'string', 'Texte'),
(NULL, '', 'fr', 'general', 'sujet', 'Sujet'),
(NULL, '', 'fr', 'general', 'sur', 'sur'),
(NULL, '', 'fr', 'general', 'svnup', 'Mettre &agrave; jour le syst&egrave;me avec SVN'),
(NULL, '', 'fr', 'general', 'sync', 'Synchroniser le site'),
(NULL, '', 'fr', 'general', 'telecharger', 'T&eacute;l&eacute;charger'),
(NULL, '', 'fr', 'general', 'template', 'Mod&egrave;le'),
(NULL, '', 'fr', 'general', 'tplemailaccountcreated', 'Votre compte a &egrave;t&egrave; cr&egrave;&egrave; sur'),
(NULL, '', 'fr', 'general', 'tplemailvisitandlogin', 'Allez sur notre site puis ins&eacute;rez les informations suivantes:'),
(NULL, '', 'fr', 'general', 'tplemailxtrainfo', 'Pour acc&eacute;der au contenu prot&eacute;g&eacute; il vous sera n&eacute;cessaire de <b>changer le mot de passe au cours de votre premier acc&egrave;s</b>.<br />Ensuite, apr&egrave;s chaque modification de mot de passe vous devrez vous authentifier de nouveau.<br />Vous aurez la possibilit&eacute; de modifier votre profil sur la page personnelle.'),
(NULL, '', 'fr', 'general', 'titre', 'Titre'),
(NULL, '', 'fr', 'general', 'tout', 'tout'),
(NULL, '', 'fr', 'general', 'type', 'Type'),
(NULL, '', 'fr', 'general', 'until', 'jusqu`au'),
(NULL, '', 'fr', 'general', 'upldb', 'Envoyer des instructions SQL'),
(NULL, '', 'fr', 'general', 'url', 'URL'),
(NULL, '', 'fr', 'general', 'versliste', 'vers la liste'),
(NULL, '', 'fr', 'general', 'ville', 'Ville'),
(NULL, '', 'fr', 'general', 'voir', 'Voir'),
(NULL, '', 'fr', 'general', 'vousinscrire', 'Vous insrire'),
(NULL, '', 'fr', 'general', 'Y', 'Oui'),
(NULL, '', 'fr', 'gendre', '1', 'Mr &amp; Mme'),
(NULL, '', 'fr', 'gendre', '2', 'Mme'),
(NULL, '', 'fr', 'gendre', '3', 'Mr'),
(NULL, '', 'fr', 'gendre', '4', 'Mlle'),
(NULL, '', 'fr', 'jour', '1', 'Dimanche'),
(NULL, '', 'fr', 'jour', '2', 'Lundi'),
(NULL, '', 'fr', 'jour', '3', 'Mardi'),
(NULL, '', 'fr', 'jour', '4', 'Mercredi'),
(NULL, '', 'fr', 'jour', '5', 'Jeudi'),
(NULL, '', 'fr', 'jour', '6', 'Vendredi'),
(NULL, '', 'fr', 'jour', '7', 'Samedi'),
(NULL, '', 'fr', 'lang', 'ar', 'Arabe'),
(NULL, '', 'fr', 'lang', 'de', 'Allemand'),
(NULL, '', 'fr', 'lang', 'en', 'Anglais'),
(NULL, '', 'fr', 'lang', 'sp', 'Espagnol'),
(NULL, '', 'fr', 'lang', 'fi', 'Finlandais'),
(NULL, '', 'fr', 'lang', 'fr', 'Fran&ccedil;ais'),
(NULL, '', 'fr', 'lang', 'it', 'Italien'),
(NULL, '', 'fr', 'lang', 'jp', 'Japonais'),
(NULL, '', 'fr', 'lang', 'no', 'Norv&eacute;gien'),
(NULL, '', 'fr', 'lang', 'ru', 'Russe'),
(NULL, '', 'fr', 'lang', 'zh', 'Chinois'),
(NULL, '', 'fr', 'mois', '2', 'F&eacute;vrier'),
(NULL, '', 'fr', 'mois', '3', 'Mars'),
(NULL, '', 'fr', 'mois', '4', 'Avril'),
(NULL, '', 'fr', 'mois', '5', 'Mai'),
(NULL, '', 'fr', 'mois', '6', 'Juin'),
(NULL, '', 'fr', 'mois', '7', 'Juillet'),
(NULL, '', 'fr', 'mois', '8', 'Ao&ucirc;t'),
(NULL, '', 'fr', 'mois', '9', 'Septembre'),
(NULL, '', 'fr', 'mois', '10', 'Octobre'),
(NULL, '', 'fr', 'mois', '11', 'Novembre'),
(NULL, '', 'fr', 'mois', '12', 'D&eacute;cembre'),
(NULL, '', 'fr', 'privilege', '1', 'Public'),
(NULL, '', 'fr', 'privilege', '2', 'Level 2'),
(NULL, '', 'fr', 'privilege', '3', 'Level 3'),
(NULL, '', 'fr', 'privilege', '4', 'Level 4'),
(NULL, '', 'fr', 'statut', 'N', 'En attente'),
(NULL, '', 'fr', 'statut', 'Y', 'Confirm&eacute;'),
(NULL, '', 'fr', 'sujet', '1', 'Mon prochain projet'),
(NULL, '', 'fr', 'sujet', '2', 'D&eacute;veloppement WEB'),
(NULL, '', 'fr', 'sujet', '3', 'Marketing Web'),
(NULL, '', 'fr', 'sujet', '4', 'Traduction'),
(NULL, '', 'fr', 'sujet', '5', 'Autre');